[server]
maxUploadSize = 500
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#9333ea"
backgroundColor = "#06020e"
secondaryBackgroundColor = "#13082a"
textColor = "#faf5ff"
font = "sans serif"
